spring.application.name=stockmarket-core

spring.config.import=optional:file:.env[.properties]
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{0} - %msg%n

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# postgresql db connection
spring.datasource.url=jdbc:postgresql://localhost:5432/stock_db
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# flyway db initialization from .sql files
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true